package com.CodeEvalCrew.AutoScore.models.Entity.Enum;

public enum Log_Enum {
    CREATE_PAPER,
    UPDATE_PAPER,
    DELETE_PAPER,
    CONFIRM_PAPER,

    CREATE_QUESTION,
    UPDATE_QUESTION,
    DELETE_QUESTION,

    CREATE_DATABASE,
    UPDATE_DATABASE,

    ADD_GHERKIN,
    GENERATE_GHERKIN,
    GENERATE_GHERKIN_MORE,
    UPDATE_GHERKIN,
    DELETE_GHERKIN,
    EXPORT_WORD,

    GENERATE_POSTMAN,
    GENERATE_POSTMAN_MORE,
    DELETE_POSTMAN,
    UPDATE_QUESTION_NUMBER_POSTMANSCRIPT,
    UPDATE_SCORE_POSTMAN_GRADING,

    IMPORT_FILE_POSTMAN,
    MERGE_POSTMAN_SCRIPT,
    UPDATE_ORDERPRIORITY_POSTMAN,
    CONFIRM_BEFORE_GRADING,
    EXPORT_FILE_POSTMAN,

    IMPORT_LIST_STUDENT,
    IMPORT_STUDENT_SOURCE_CODE,

    START_GRADING,

    EXPORT_FILE_SCORE

}
